steps:
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  env: ['GIT_DISCOVERY_ACROSS_FILESYSTEM=1']
  args:
    - '-c'
    - |
      git init
      git clean -x -d -f .
      git remote add origin https://github.com/The-OpenROAD-Project/OpenROAD.git
      git fetch origin $BRANCH_NAME
      git checkout $COMMIT_SHA
      git submodule update --init --recursive
- name: 'gcr.io/kaniko-project/executor'
  args:
    - --destination=${_GCR_ZONE}/$PROJECT_ID/${_IMAGE_NAME}:${SHORT_SHA}
    - --cache=true
    - --cache-ttl=168h
options:
 diskSizeGb: 200
 machineType: 'N1_HIGHCPU_8'
timeout: '7200s'
substitutions:
  _GCR_ZONE: 'gcr.io'
  _IMAGE_NAME: 'openroad'
