steps:
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  env: ['GIT_DISCOVERY_ACROSS_FILESYSTEM=1']
  args:
    - '-c'
    - |
      git init
      git clean -x -d -f .
      git remote add origin https://github.com/The-OpenROAD-Project/OpenROAD.git
      git fetch origin $BRANCH_NAME
      git checkout $COMMIT_SHA
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_GCR_ZONE}/$PROJECT_ID/${_IMAGE_NAME}:${SHORT_SHA}'
    - '.'
options:
 diskSizeGb: 200
timeout: '7200s'
substitutions:
  _GCR_ZONE: 'gcr.io'
  _IMAGE_NAME: 'openroad'
images:
  - '${_GCR_ZONE}/$PROJECT_ID/${_IMAGE_NAME}:${SHORT_SHA}'
